version: '1.1.{build}'
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: /nFpn8Q/Ml4YE1swuD26sqoAj9CFEXhStCxhAsFEXsAWZJDXcSGJ1ECgprM6101L
before_build:
  - nuget restore ".\Gelf4NLog.sln"
build:
  project: .\Gelf4NLog.sln
  verbosity: minimal
test:
  assemblies:
    - Gelf4NLog.UnitTest
after_test:
  - ps: .\coveralls.ps1
notifications:
  - provider: Email
    to:
      - devadmin@certegy.com.au
      - ryan.bartsch@certegy.com.au
  - provider: Slack
    auth_token:
      secure: QWE2vFI2LUFAu+jx4lXHihtpPFoVi+ru0mHSC/BvsyXYcRvgh7Tc8zEEaKkj1n5V09+Ti39CvVooS3Y8VTn7PYC6lef2OrQQ+ivqkJL+lZI=
    channel: '#alerts'